# Generated by Django 4.0.5 on 2022-06-05 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_link', models.CharField(max_length=500, verbose_name='Посилання на відео')),
                ('video_name', models.CharField(max_length=75, verbose_name='Назва відео')),
            ],
            options={
                'verbose_name': 'Відео',
                'verbose_name_plural': 'Відео',
            },
        ),
    ]
